# Generated by Django 2.2.4 on 2019-08-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20190809_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='\x7fdefaultName', max_length=40),
            preserve_default=False,
        ),
    ]
